spring:
  application:
    name: intranet-server

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/intranet?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: gktjdwns1030!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

# JWT
jwt:
  secret: dcom-intranet-server-jwt-secret-key-must-be-long-enough-for-256-bits-security
  access-token-validity: 1800000
  refresh-token-validity: 1209600000